### ISSUE TITLE
left-over cursor theme?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-xfce-settings#1]
Is this debris from somewhere or any clever idea behind that that I don't understand?
https://github.com/manjaro/manjaro-xfce-settings/blob/master/skel/.local/share/icons/default/index.theme#L2

**Comment by oberon2007** [comment]
the minimal settings dir has it, too ...

**Comment by Kirek** [comment]
Yeah, some old setting, probably pre-menda, should be removed imo.
