### ISSUE TITLE
shall we include FF userChrome.css ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-xfce-settings#2]
The default FF looks like this:
![default](https://cloud.githubusercontent.com/assets/11800714/14589918/176c26f8-04ee-11e6-97b0-c56ce843ac56.png)

using **Vertex-Maia**'s .css file like this:
![themed](https://cloud.githubusercontent.com/assets/11800714/14589923/338bb038-04ee-11e6-8142-24c9f054614f.png)

To use it we could simply install a default profile directory in **skel/.mozilla/firefox** containing nothing but a symlink to **/usr/share/themes/Firefox/chrome**

**Comment by Ste74** [comment]
I use it ... why not install it via .js in firefox setting .. i love dark
theme but is my preference :p

2016-04-17 22:49 GMT+02:00 Bernhard Landauer <notifications@github.com>:

**Comment by oberon2007** [comment]
How do you use it via .js?

**Comment by Ste74** [comment]
I think is equal at arc-theme-firefox. Try install it... then see my
manjaro-budgie-extra-setting pkg
Il 17/apr/2016 23:08, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
I see. Just, **vertex** installs in a completely different way. It's just a chrome folder in **/usr/share/themes/Firefox**. Specifying the theme in the **/usr/lib/.../....js** doesn't work.

**Comment by Ste74** [comment]
Right, but i want see if possible create a .xpi file for vertex manjaro: )
Il 18/apr/2016 01:07, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by Ste74** [comment]
Why not fork arc-firefox-theme and in the build option disable other theme (light and darker ) like this
./autogen.sh --prefix=/usr --disable-light --disable-darker 
sudo make install
the dark theme is the same ( at my eye ) at the image in your first post ..

**Comment by oberon2007** [comment]
hm. I don't think it is very similar. First of all: It's blue! :laughing:

**Comment by Ste74** [comment]
:sweat_smile: my apologise .. clean all , removed arc-firefox-theme via pacman and yes .. now is different .. :stuck_out_tongue_winking_eye: .. ok so if vertex manjaro is the default theme for manjaro why not put in shared folder ? Is possible ?

**Comment by oberon2007** [comment]
I think shared is not so good. But it could be either in **manjaro-browser-settings** package, or simply in the settings package of the profiles that want to use it.

**Comment by Ste74** [comment]
Yes, better i think in setting browser but via optdep and create a new pkg
to put chrome.css. in this way if a user want build an iso but without dark
theme and only with manjaro browser setting is easy. After via desktop
setting maintainer can choice if use or not...
Il 18/apr/2016 23:16, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
I just demonstrate what I mean :wink: 
@philmmanjaro please revert if you don't like it!

**Comment by Ste74** [comment]
@oberon2007 so whit this new iso created is ok but for older installation ? The user have to create manually the symlink right ? If an additional pkg create in skel the symlink the user can login e logout and the symlink is generated in Home user or not ?

**Comment by oberon2007** [comment]
U-uuuh, the content of **/etc/skel** is only copied for a newl user! The package would have to create the symlink in the actual user home - but that's a bit of a nono ... :wink:

**Comment by oberon2007** [comment]
And on top of that you will not know which firefox profile to create the link in! :laughing: 
They will just have to do it manually.

**Comment by Ste74** [comment]
Ok sometimes the brain is offline :wink: 
Look this @oberon2007 https://github.com/manjaro/packages-community/commit/bca8e57ad758b93141381e2bad8ae80da4c646a8 if don't like revert :stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-xfce-settings/commit/c9aed1c2b3610aad3685086aaba7520fb91446e2
