### ISSUE TITLE
Verve Command Line background color

### ISSUE THREAD

**Issue by sfosset** [manjaro/manjaro-xfce-settings#4]
I am using xfce4-verve-plugin with Manjaro 16.06 rc1 xfce edition. 
When the session starts, the background color of the input block in the xfce panel is grey (following my current desktop style Vertex-Maia-Dark). When I am writing in the input block, the background color is Maia-green. Everything is alright so far.
But when I unfocus the intput block, the background become white. The behavior should be to return to the initial grey color right ?

![bg_issue](https://cloud.githubusercontent.com/assets/9079710/15633161/81ce9886-25a6-11e6-9c5d-11e913853c2d.png)

The solution is probably to add some lines to the Maia template, but I wasn't able to find a working solution myself.

**Comment by philmmanjaro** [comment]
Obsolete? Please open a [new issue](https://bugs.manjaro.org) if still needed.
